export const IPC_CHANNELS = {
  shell: {
    getSnapshot: "shell:getSnapshot",
  },
  agent: {
    event: "agent:event",
    getProviders: "agent:getProviders",
    getSettings: "agent:getSettings",
    getSnapshot: "agent:getSnapshot",
    prompt: "agent:prompt",
    cancelPrompt: "agent:cancelPrompt",
    reset: "agent:reset",
    switchModel: "agent:switchModel",
    getDiscovery: "agent:getDiscovery",
    getSlashSuggestions: "agent:getSlashSuggestions",
  },
  repositories: {
    add: "repositories:add",
    reorder: "repositories:reorder",
    select: "repositories:select",
    remove: "repositories:remove",
    openInFinder: "repositories:openInFinder",
  },
  worktrees: {
    create: "worktrees:create",
    select: "worktrees:select",
  },
  threads: {
    create: "threads:create",
    select: "threads:select",
    archive: "threads:archive",
    delete: "threads:delete",
  },
  dialog: {
    showOpenDialog: "dialog:showOpenDialog",
    openExternal: "dialog:openExternal",
  },
  fs: {
    readDirectory: "fs:readDirectory",
    readFile: "fs:readFile",
    writeFile: "fs:writeFile",
    getImageMetadata: "fs:getImageMetadata",
    getImagePreview: "fs:getImagePreview",
  },
  git: {
    getRepositoryStatus: "git:getRepositoryStatus",
    stageFile: "git:stageFile",
    unstageFile: "git:unstageFile",
    discardFile: "git:discardFile",
    commit: "git:commit",
    pull: "git:pull",
    push: "git:push",
  },
  packages: {
    event: "packages:event",
    getManagerStatus: "packages:getManagerStatus",
    searchCatalog: "packages:searchCatalog",
    getPackageDetail: "packages:getPackageDetail",
    listInstalled: "packages:listInstalled",
    install: "packages:install",
    remove: "packages:remove",
    update: "packages:update",
  },
  terminal: {
    create: "terminal:create",
    write: "terminal:write",
    resize: "terminal:resize",
    destroy: "terminal:destroy",
    getSessions: "terminal:getSessions",
  },
  search: {
    searchFiles: "search:searchFiles",
  },
  state: {
    getRepositoryPreferences: "state:getRepositoryPreferences",
    updateRepositoryPreferences: "state:updateRepositoryPreferences",
    getWorkspaceSession: "state:getWorkspaceSession",
    saveWorkspaceSession: "state:saveWorkspaceSession",
    getAppPreferences: "state:getAppPreferences",
    updateAppPreferences: "state:updateAppPreferences",
    importLegacyPreferences: "state:importLegacyPreferences",
  },
  window: {
    create: "window:create",
    close: "window:close",
    focus: "window:focus",
    fullscreenChanged: "window:fullscreenChanged",
    getFullscreenState: "window:getFullscreenState",
    move: "window:move",
    resize: "window:resize",
    minimize: "window:minimize",
    maximize: "window:maximize",
    restore: "window:restore",
    getLayout: "window:getLayout",
  },
} as const;

export type IpcChannels = typeof IPC_CHANNELS;
