export const IPC_CHANNELS = {
  shell: {
    getSnapshot: "shell:getSnapshot",
  },
  agent: {
    event: "agent:event",
    getProviders: "agent:getProviders",
    getSettings: "agent:getSettings",
    getSnapshot: "agent:getSnapshot",
    getOAuthProviders: "agent:getOAuthProviders",
    loginWithOAuth: "agent:loginWithOAuth",
    logoutOAuth: "agent:logoutOAuth",
    prompt: "agent:prompt",
    cancelPrompt: "agent:cancelPrompt",
    reset: "agent:reset",
    switchModel: "agent:switchModel",
    getDiscovery: "agent:getDiscovery",
    getSlashSuggestions: "agent:getSlashSuggestions",
  },
  repositories: {
    add: "repositories:add",
    reorder: "repositories:reorder",
    select: "repositories:select",
    remove: "repositories:remove",
    openInFinder: "repositories:openInFinder",
  },
  worktrees: {
    create: "worktrees:create",
    select: "worktrees:select",
    remove: "worktrees:remove",
  },
  threads: {
    create: "threads:create",
    select: "threads:select",
    delete: "threads:delete",
  },
  dialog: {
    showOpenDialog: "dialog:showOpenDialog",
    openExternal: "dialog:openExternal",
  },
  fs: {
    readDirectory: "fs:readDirectory",
    readFile: "fs:readFile",
    writeFile: "fs:writeFile",
    deleteFile: "fs:deleteFile",
    renameFile: "fs:renameFile",
    moveFile: "fs:moveFile",
  },
  git: {
    getRepositoryStatus: "git:getRepositoryStatus",
    isRepository: "git:isRepository",
    init: "git:init",
    diffFile: "git:diffFile",
    stageFile: "git:stageFile",
    stageFiles: "git:stageFiles",
    unstageFile: "git:unstageFile",
    unstageFiles: "git:unstageFiles",
    discardFile: "git:discardFile",
    commit: "git:commit",
    fetch: "git:fetch",
    pull: "git:pull",
    push: "git:push",
  },
  packages: {
    event: "packages:event",
    getManagerStatus: "packages:getManagerStatus",
    searchCatalog: "packages:searchCatalog",
    getPackageDetail: "packages:getPackageDetail",
    listInstalled: "packages:listInstalled",
    install: "packages:install",
    remove: "packages:remove",
    update: "packages:update",
  },
  terminal: {
    create: "terminal:create",
    write: "terminal:write",
    resize: "terminal:resize",
    destroy: "terminal:destroy",
    getSessions: "terminal:getSessions",
    event: "terminal:event",
  },
  search: {
    searchFiles: "search:searchFiles",
  },
  state: {
    getRepositoryPreferences: "state:getRepositoryPreferences",
    updateRepositoryPreferences: "state:updateRepositoryPreferences",
    getWorkspaceSession: "state:getWorkspaceSession",
    saveWorkspaceSession: "state:saveWorkspaceSession",
    getAppPreferences: "state:getAppPreferences",
    updateAppPreferences: "state:updateAppPreferences",
    importLegacyPreferences: "state:importLegacyPreferences",
  },
  window: {
    fullscreenChanged: "window:fullscreenChanged",
    getFullscreenState: "window:getFullscreenState",
  },
  clipboard: {
    writeText: "clipboard:writeText",
  },
} as const;

export type IpcChannels = typeof IPC_CHANNELS;
